# Add `~/.bin` to the `$PATH`
export PATH="$HOME/.bin:$PATH";

export TERM="xterm-256color"

# Init antigen
source $(brew --prefix)/share/antigen/antigen.zsh

# Load the oh-my-zsh's library
antigen use oh-my-zsh

antigen bundles <<EOBUNDLES

    brew
    docker
    docker-compose
    encode64
    git
    httpie
    pip
    pipenv
    sdk
    ssh
    ssh-agent

    # Extra zsh completions
    zsh-users/zsh-completions

    # Fish-like auto suggestions
    zsh-users/zsh-autosuggestions

    # Syntax highlighting bundle.
    zsh-users/zsh-syntax-highlighting

EOBUNDLES

# Tell antigen that you're done
antigen apply

# Configure atuin
eval "$(atuin init zsh)"

# Configure starship
eval "$(starship init zsh)"

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --zsh)"

# Set Default Editor
export EDITOR='zed'

export ENABLE_CORRECTION='false'

# Update Homebrew every 24 hours
export HOMEBREW_AUTO_UPDATE_SECS="86400"

# Source local extra (private) settings specific to machine if it exists
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

source ~/.bin/aliases.zsh
source ~/.bin/config.zsh
source ~/.bin/functions.zsh

export FZF_DEFAULT_OPTS=" \
--color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796 \
--color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
--color=marker:#b7bdf8,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796 \
--color=selected-bg:#494d64 \
--multi"

fpath=($(brew --prefix)/share/zsh-completions $(brew --prefix)/share/zsh/site-functions $fpath)

# GNU Sed
SED_PATH="$(brew --prefix gnu-sed)/libexec/gnubin"
# GNU Core Utilities
COREUTILS_PATH="$(brew --prefix coreutils)/libexec/gnubin"

export PATH="$SED_PATH:$COREUTILS_PATH:$PATH"

# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
