# Add `~/.bin` to the `$PATH`
export PATH="$HOME/.bin:$PATH";

export TERM="xterm-256color"

# Change Antidote's home directory
export ANTIDOTE_HOME=~/.cache/antidote

# Init antidote
source $(brew --prefix)/share/antidote/antidote.zsh

# Initialize plugins statically with ${ZDOTDIR:-~}/.zsh_plugins.txt
antidote load

# Configure atuin
eval "$(atuin init zsh)"

# Configure starship
eval "$(starship init zsh)"

# Set up fzf key bindings and fuzzy completion
eval "$(fzf --zsh)"

# Set Default Editor
export EDITOR='zed'

export ENABLE_CORRECTION='false'

# Update Homebrew every 24 hours
export HOMEBREW_AUTO_UPDATE_SECS="86400"
# Hide Homebrew usage hints
export HOMEBREW_NO_ENV_HINTS=1

# Source local extra (private) settings specific to machine if it exists
if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

source ~/.bin/aliases.zsh
source ~/.bin/config.zsh
source ~/.bin/functions.zsh

export FZF_DEFAULT_OPTS=" \
--color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796 \
--color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
--color=marker:#b7bdf8,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796 \
--color=selected-bg:#494d64 \
--multi"

fpath=($(brew --prefix)/share/zsh-completions $(brew --prefix)/share/zsh/site-functions $fpath)

# GNU Sed
SED_PATH="$(brew --prefix gnu-sed)/libexec/gnubin"
# GNU Core Utilities
COREUTILS_PATH="$(brew --prefix coreutils)/libexec/gnubin"
# Unversioned symlinks for python, python-config, pip etc. are installed here
PYTHON_PATH="$(brew --prefix python)/libexec/bin"

export PATH="$SED_PATH:$COREUTILS_PATH:$PYTHON_PATH:$PATH"

# 1Password SSH Agent
export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock

# THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
